### ISSUE TITLE
您好，我在编译时遇到了eigen报错的问题

### ISSUE THREAD

**Issue by af-doom** [Stan994265/mVIL-Fusion#4]
/home/wyw/ROS1_PROJECT/2023/VIL_ROS_calib/src/mVIL-Fusion/lidar_mapping/include/fast_gicp/gicp/fast_vgicp_voxel.hpp:19:7: error: no matching function for call to ‘std::vector<Eigen::Matrix<int, 3, 1>, Eigen::aligned_allocator<Eigen::Matrix<int, 3, 1> > >::vector(<brace-enclosed initializer list>)’
   19 |       };
      |       ^

**Comment by Stan994265** [comment]
这个库编译请参考https://github.com/SMRT-AIST/fast_gicp
