### ISSUE TITLE
catkin  error  fast gicp   my eigen3.3.7

### ISSUE THREAD

**Issue by af-doom** [Stan994265/mVIL-Fusion#5]
mVIL-Fusion/lidar_mapping/include/fast_gicp/gicp/fast_vgicp_voxel.hpp:159:50: error: ‘const class Eigen::CwiseUnaryOp<Eigen::internal::scalar_add_op<double>, const Eigen::CwiseUnaryOp<Eigen::internal::scalar_quotient1_op<double>, const Eigen::ArrayWrapper<const Eigen::Matrix<double, 4, 1> > > >’ has no member named ‘floor’
  159 |     return (x.array() / voxel_resolution_ - 0.5).floor().template cast<int>().template head<3>();
      |                                                  ^~~~~
/home/wyw/ROS1_PROJECT/2023/VIL_ROS_calib/src/mVIL-Fusion/lidar_mapping/include/fast_gicp/gicp/fast_vgicp_voxel.hpp:159:72: error: expected primary-expression before ‘int’
  159 |     return (x.array() / voxel_resolution_ - 0.5).floor().template cast<int>().template head<3>();

**Comment by reachel1** [comment]
me too!
error: ‘const class Eigen::CwiseUnaryOp<Eigen::internal::scalar_add_op<double>, const Eigen::CwiseUnaryOp<Eigen::internal::scalar_quotient1_op<double>, const Eigen::ArrayWrapper<const Eigen::Matrix<double, 4, 1> > > >’ has no member named ‘floor’
  168 |     return (x.array() / voxel_resolution_ - 0.5).floor().template cast<int>().template head<3>();
how can i deel it?

**Comment by nancy12347** [comment]
> mVIL-Fusion/lidar_mapping/include/fast_gicp/gicp/fast_vgicp_voxel.hpp:159:50: error: ‘const class Eigen::CwiseUnaryOp<Eigen::internal::scalar_add_op, const Eigen::CwiseUnaryOp<Eigen::internal::scalar_quotient1_op, const Eigen::ArrayWrapper<const Eigen::Matrix<double, 4, 1> > > >’ has no member named ‘floor’ 159 | return (x.array() / voxel_resolution_ - 0.5).floor().template cast().template head<3>(); | ^~~~~ /home/wyw/ROS1_PROJECT/2023/VIL_ROS_calib/src/mVIL-Fusion/lidar_mapping/include/fast_gicp/gicp/fast_vgicp_voxel.hpp:159:72: error: expected primary-expression before ‘int’ 159 | return (x.array() / voxel_resolution_ - 0.5).floor().template cast().template head<3>();

how did you solved this problem?
